#!/usr/bin/env python3
"""Generate the six VOICEVOX voices for the bundled sample demo deck.

The full library's audio is generated by convert.py from raw_data/, but the
hand-authored sample deck (data/sample/, the only deck shipped publicly) has no
audio. This script synthesizes each sample card's reading in all six shipped
voices so the public web demo can show off multi-voice playback.

Prereqs: the VOICEVOX engine running locally (launch the VOICEVOX app) and
ffmpeg on PATH. Resumable — existing clips are kept. Run from the project root:

    python3 scripts/sample-tts.py
"""
import json
import os
import shutil
import subprocess
import sys
import urllib.parse
import urllib.request
from pathlib import Path

VV = os.environ.get("VOICEVOX_HOST", "http://127.0.0.1:50021")
# (key, VOICEVOX style id) — keep in sync with src/speakers.js & convert.py.
SPEAKERS = [("aoyama", 13), ("kyushu", 17), ("yurei", 103), ("zunda", 3), ("no7", 30), ("metan", 6)]
SAMPLE = Path("data/sample")


def vv_post(path, data=None):
    headers = {"Content-Type": "application/json"} if data is not None else {}
    req = urllib.request.Request(f"{VV}{path}", data=data, method="POST", headers=headers)
    return urllib.request.urlopen(req, timeout=60).read()


def synth(text, style_id, dest):
    q = vv_post(f"/audio_query?text={urllib.parse.quote(text)}&speaker={style_id}")
    wav = vv_post(f"/synthesis?speaker={style_id}", data=q)
    p = subprocess.run(
        ["ffmpeg", "-y", "-loglevel", "error", "-f", "wav", "-i", "pipe:0",
         "-codec:a", "libmp3lame", "-qscale:a", "5", str(dest)],
        input=wav, capture_output=True,
    )
    return p.returncode == 0 and dest.exists()


def main():
    try:
        ver = urllib.request.urlopen(f"{VV}/version", timeout=5).read().decode().strip()
    except Exception as e:  # noqa: BLE001
        sys.exit(f"VOICEVOX not reachable at {VV} ({e}) — launch the VOICEVOX app first.")
    if not shutil.which("ffmpeg"):
        sys.exit("ffmpeg not found — install it (brew install ffmpeg).")
    print(f"[tts] VOICEVOX {ver} · {len(SPEAKERS)} voices")

    made = skipped = failed = 0
    for jf in sorted(SAMPLE.glob("*.json")):
        if jf.name == "manifest.json":
            continue
        data = json.loads(jf.read_text(encoding="utf-8"))
        cards = data["cards"] if isinstance(data, dict) else data
        for card in cards:
            text = card.get("reading") or card.get("front")
            if not text:
                continue
            adir = SAMPLE / "audio" / card["id"]
            adir.mkdir(parents=True, exist_ok=True)
            audio = card.get("audio") or {}
            for key, sid in SPEAKERS:
                dest = adir / f"{key}.mp3"
                rel = f"sample/audio/{card['id']}/{key}.mp3"
                if dest.exists() and dest.stat().st_size > 0:
                    audio[key] = rel
                    skipped += 1
                    continue
                try:
                    if synth(text, sid, dest):
                        audio[key] = rel
                        made += 1
                    else:
                        failed += 1
                except Exception as e:  # noqa: BLE001
                    print(f"  fail {card['id']} {key}: {e}")
                    failed += 1
            card["audio"] = audio
        jf.write_text(json.dumps(data, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
        print(f"  {jf.name}: {len(cards)} cards")
    print(f"[tts] made {made}, skipped {skipped}, failed {failed}")


if __name__ == "__main__":
    main()
